[env]
POSTGRES_PASSWORD='password'
POSTGRES_USER='postgres'
CAFEPHILO_V3_DATABASE_NAME='cafephilo_v3_development'
CAFEPHILO_V3_DATABASE_USER='postgres'
CAFEPHILO_V3_DATABASE_PASSWORD='password'
CAFEPHILO_V3_DATABASE_TEST_NAME='cafephilo_v3_test'
CAFEPHILO_V3_DATABASE_TEST_USER='postgres'
CAFEPHILO_V3_DATABASE_TEST_PASSWORD='password'

# REcapcha
RECAPTCHA_SITE_KEY="6LdgFWMaAAAAAGz_qmpxdUomXmlNH71J1vb1eSme"
RECAPTCHA_SECRET_KEY="6LdgFWMaAAAAADeC3Hgj4hP5Bg72OAHafpKCNqUA"

[tools]
node = "14"
ruby = "3.1"
